### ISSUE TITLE
Cramfs compile error

### ISSUE THREAD

**Issue by schneemaier** [stokie-ant/xm510_firmtool#2]
I tried to unpack the firmware with the tool, but receive a cramfs compile error:

root@SchneeUS:/home/schnee/Workspace/xm510_firmtool# ./firmtool unpack ./General_XM510_50X10.Nat.OnvifS_V5.00.R01.20170718_all.bin 
make: Entering directory '/home/schnee/Workspace/xm510_firmtool/src/cramfs-1.1'
gcc -W -Wall -O2 -g -I.   mkcramfs.c  -lz -o mkcramfs
mkcramfs.c: In function ‘parse_directory’:
mkcramfs.c:245:40: warning: passing argument 4 of ‘scandir’ from incompatible pointer type [-Wincompatible-pointer-types]
  245 |  dircount = scandir(name, &dirlist, 0, cramsort);
      |                                        ^~~~~~~~
      |                                        |
      |                                        int (*)(const void *, const void *)
In file included from mkcramfs.c:31:
/usr/include/dirent.h:258:13: note: expected ‘int (*)(const struct dirent **, const struct dirent **)’ but argument is of type ‘int (*)(const void *, const void *)’
  258 |       int (*__cmp) (const struct dirent **,
      |       ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  259 |       const struct dirent **))
      |       ~~~~~~~~~~~~~~~~~~~~~~~
mkcramfs.c:287:15: warning: pointer targets in assignment from ‘char *’ to ‘unsigned char *’ differ in signedness [-Wpointer-sign]
  287 |   entry->name = strdup(dirent->d_name);
      |               ^
mkcramfs.c: In function ‘write_superblock’:
mkcramfs.c:399:16: warning: pointer targets in passing argument 1 of ‘strncpy’ differ in signedness [-Wpointer-sign]
  399 |   strncpy(super->name, opt_name, sizeof(super->name));
      |           ~~~~~^~~~~~
      |                |
      |                u8 * {aka unsigned char *}
In file included from /usr/include/features.h:461,
                 from /usr/include/x86_64-linux-gnu/sys/types.h:25,
                 from mkcramfs.c:25:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:103:1: note: expected ‘char * restrict’ but argument is of type ‘u8 *’ {aka ‘unsigned char *’}
  103 | __NTH (strncpy (char *__restrict __dest, const char *__restrict __src,
      | ^~~~~
mkcramfs.c:401:16: warning: pointer targets in passing argument 1 of ‘strncpy’ differ in signedness [-Wpointer-sign]
  401 |   strncpy(super->name, "Compressed", sizeof(super->name));
      |           ~~~~~^~~~~~
      |                |
      |                u8 * {aka unsigned char *}
In file included from /usr/include/features.h:461,
                 from /usr/include/x86_64-linux-gnu/sys/types.h:25,
                 from mkcramfs.c:25:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:103:1: note: expected ‘char * restrict’ but argument is of type ‘u8 *’ {aka ‘unsigned char *’}
  103 | __NTH (strncpy (char *__restrict __dest, const char *__restrict __src,
      | ^~~~~
mkcramfs.c: In function ‘print_node’:
mkcramfs.c:445:33: warning: implicit declaration of function ‘major’ [-Wimplicit-function-declaration]
  445 |   snprintf(info, 10, "%4d,%4d", major(e->size), minor(e->size));
      |                                 ^~~~~
mkcramfs.c:445:49: warning: implicit declaration of function ‘minor’; did you mean ‘mincore’? [-Wimplicit-function-declaration]
  445 |   snprintf(info, 10, "%4d,%4d", major(e->size), minor(e->size));
      |                                                 ^~~~~
      |                                                 mincore
mkcramfs.c: In function ‘write_directory_structure’:
mkcramfs.c:480:29: warning: pointer targets in passing argument 1 of ‘strlen’ differ in signedness [-Wpointer-sign]
  480 |    size_t len = strlen(entry->name);
      |                        ~~~~~^~~~~~
      |                             |
      |                             unsigned char *
In file included from mkcramfs.c:34:
/usr/include/string.h:385:35: note: expected ‘const char *’ but argument is of type ‘unsigned char *’
  385 | extern size_t strlen (const char *__s)
      |                       ~~~~~~~~~~~~^~~
mkcramfs.c: In function ‘do_compress’:
mkcramfs.c:598:25: warning: pointer targets in passing argument 1 of ‘compress2’ differ in signedness [-Wpointer-sign]
  598 |    err = compress2(base + curr, &len, uncompressed, input, Z_BEST_COMPRESSION);
      |                    ~~~~~^~~~~~
      |                         |
      |                         char *
In file included from /usr/include/zlib.h:34,
                 from mkcramfs.c:37:
/usr/include/zlib.h:1243:31: note: expected ‘Bytef *’ {aka ‘unsigned char *’} but argument is of type ‘char *’
 1243 | ZEXTERN int ZEXPORT compress2 OF((Bytef *dest,   uLongf *destLen,
      |                               ^~
mkcramfs.c:598:39: warning: pointer targets in passing argument 3 of ‘compress2’ differ in signedness [-Wpointer-sign]
  598 |    err = compress2(base + curr, &len, uncompressed, input, Z_BEST_COMPRESSION);
      |                                       ^~~~~~~~~~~~
      |                                       |
      |                                       char *
In file included from /usr/include/zlib.h:34,
                 from mkcramfs.c:37:
/usr/include/zlib.h:1243:31: note: expected ‘const Bytef *’ {aka ‘const unsigned char *’} but argument is of type ‘char *’
 1243 | ZEXTERN int ZEXPORT compress2 OF((Bytef *dest,   uLongf *destLen,
      |                               ^~
mkcramfs.c: In function ‘write_data’:
mkcramfs.c:647:45: warning: pointer targets in passing argument 3 of ‘do_compress’ differ in signedness [-Wpointer-sign]
  647 |     offset = do_compress(base, offset, entry->name, entry->uncompressed, entry->size);
      |                                        ~~~~~^~~~~~
      |                                             |
      |                                             unsigned char *
mkcramfs.c:578:78: note: expected ‘const char *’ but argument is of type ‘unsigned char *’
  578 | static unsigned int do_compress(char *base, unsigned int offset, char const *name, char *uncompressed, unsigned int size)
      |                                                                  ~~~~~~~~~~~~^~~~
mkcramfs.c: In function ‘main’:
mkcramfs.c:771:59: warning: format ‘%Ld’ expects argument of type ‘long long int’, but argument 3 has type ‘loff_t’ {aka ‘long int’} [-Wformat=]
  771 |    "warning: estimate of required size (upper bound) is %LdMB, but maximum image size is %uMB, we might die prematurely\n",
      |                                                         ~~^
      |                                                           |
      |                                                           long long int
      |                                                         %ld
  772 |    fslen_ub >> 20,
      |    ~~~~~~~~~~~~~~                                          
      |             |
      |             loff_t {aka long int}
mkcramfs.c:810:27: warning: format ‘%d’ expects argument of type ‘int’, but argument 2 has type ‘ssize_t’ {aka ‘long int’} [-Wformat=]
  810 |  printf("Directory data: %d bytes\n", offset);
      |                          ~^           ~~~~~~
      |                           |           |
      |                           int         ssize_t {aka long int}
      |                          %ld
mkcramfs.c:817:23: warning: format ‘%d’ expects argument of type ‘int’, but argument 2 has type ‘ssize_t’ {aka ‘long int’} [-Wformat=]
  817 |  printf("Everything: %d kilobytes\n", offset >> 10);
      |                      ~^               ~~~~~~~~~~~~
      |                       |                      |
      |                       int                    ssize_t {aka long int}
      |                      %ld
mkcramfs.c:821:24: warning: format ‘%d’ expects argument of type ‘int’, but argument 2 has type ‘long unsigned int’ [-Wformat=]
  821 |  printf("Super block: %d bytes\n", sizeof(struct cramfs_super));
      |                       ~^           ~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                        |           |
      |                        int         long unsigned int
      |                       %ld
mkcramfs.c:825:29: warning: pointer targets in passing argument 2 of ‘crc32’ differ in signedness [-Wpointer-sign]
  825 |  crc = crc32(crc, (rom_image+opt_pad), (offset-opt_pad));
      |                   ~~~~~~~~~~^~~~~~~~~
      |                             |
      |                             char *
In file included from /usr/include/zlib.h:34,
                 from mkcramfs.c:37:
/usr/include/zlib.h:1726:31: note: expected ‘const Bytef *’ {aka ‘const unsigned char *’} but argument is of type ‘char *’
 1726 | ZEXTERN uLong ZEXPORT crc32   OF((uLong crc, const Bytef *buf, uInt len));
      |                               ^~
mkcramfs.c:705:4: warning: this statement may fall through [-Wimplicit-fallthrough=]
  705 |    usage(MKFS_OK);
      |    ^~~~~~~~~~~~~~
mkcramfs.c:706:3: note: here
  706 |   case 'E':
      |   ^~~~
In file included from /usr/include/string.h:495,
                 from mkcramfs.c:34:
In function ‘strncpy’,
    inlined from ‘write_superblock’ at mkcramfs.c:399:3,
    inlined from ‘main’ at mkcramfs.c:820:2:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:106:10: warning: ‘__builtin_strncpy’ specified bound 16 equals destination size [-Wstringop-truncation]
  106 |   return __builtin___strncpy_chk (__dest, __src, __len, __bos (__dest));
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/bin/ld: /tmp/cciDkmuP.o: in function `print_node':
/home/schnee/Workspace/xm510_firmtool/src/cramfs-1.1/mkcramfs.c:445: undefined reference to `minor'
/usr/bin/ld: /home/schnee/Workspace/xm510_firmtool/src/cramfs-1.1/mkcramfs.c:445: undefined reference to `major'
collect2: error: ld returned 1 exit status
make: *** [<builtin>: mkcramfs] Error 1
make: Leaving directory '/home/schnee/Workspace/xm510_firmtool/src/cramfs-1.1'
Something broke while compiling cramfs...

Environment: Latest Ubuntu, kernel 5.4

Not sure what I am doing wrong. There is only one occurrence for minor and major in the code on line 445

**Comment by stokie-ant** [comment]
Yes, I've had this with a lot of software since upgrading to Debian 10
#include <sys/sysmacros.h>
In mkcramfs.c

**Comment by schneemaier** [comment]
Thanks! This fixed the compile issue
